/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_east_jni07_NdkSample */

#ifndef _Included_com_east_jni07_NdkSample
#define _Included_com_east_jni07_NdkSample
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_east_jni07_NdkSample
 * Method:    getSingnaturePassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_east_jni07_NdkSample_getSingnaturePassword
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
